data = {
    "triggers": [
        "thank",
        "thanks",
        "thx",
        "appreciate",
        "grateful",
        "gracias",
        "agradezco",
        "agradecido",
        "agradecida",
        "merci",
        "remercie",
        "reconnaissant",
        "reconnaissante",
    ],
    "answers": {
        "en": [
            "You're very welcome! Happy I could help. 😊",
            "Anytime! Let me know if you want to know more about my work.",
            "Glad I could help! Is there anything else you're curious about?",
            "No problem at all! I'm here if you have more questions.",
            "My pleasure! Feel free to keep exploring my portfolio.",
        ],
        "es": [
            "¡De nada! Un placer haberte ayudado. 😊",
            "¡Cuando quieras! Avísame si quieres saber más sobre mi trabajo.",
            "¡Me alegra haberte ayudado! ¿Hay algo más sobre lo que tengas curiosidad?",
            "¡No hay problema! Aquí estaré si tienes más preguntas.",
            "¡El placer es mío! Siéntete libre de seguir explorando mi portafolio.",
        ],
        "fr": [
            "De rien ! Heureux d'avoir pu vous aider. 😊",
            "Je vous en prie ! N'hésitez pas si vous voulez en savoir plus sur mon travail.",
            "Ravi d'avoir pu aider ! Y a-t-il autre chose qui vous intrigue ?",
            "Pas de problème du tout ! Je suis là si vous avez d'autres questions.",
            "Tout le plaisir est pour moi ! N'hésitez pas à continuer à explorer mon portfolio.",
        ],
    },
}
