# Generated by Django 5.2.8 on 2025-11-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(max_length=400)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("role", models.CharField(max_length=50)),
                ("features", models.CharField(max_length=100)),
                ("challenges", models.TextField(blank=True)),
                ("project_type", models.CharField(max_length=100)),
                ("live_demo_url", models.URLField(blank=True)),
                ("source_code_url", models.URLField(blank=True)),
                (
                    "screenshot_01",
                    models.ImageField(
                        blank=True, null=True, upload_to="project_screenshots/"
                    ),
                ),
                (
                    "screenshot_02",
                    models.ImageField(
                        blank=True, null=True, upload_to="project_screenshots/"
                    ),
                ),
                (
                    "screenshot_03",
                    models.ImageField(
                        blank=True, null=True, upload_to="project_screenshots/"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("technologies", models.ManyToManyField(to="projects.technology")),
            ],
        ),
    ]
