"""initial baseline

Revision ID: 3a40d1099870
Revises:
Create Date: 2026-05-18 21:51:14.040423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "3a40d1099870"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "about",
        sa.Column("p1_en", sqlmodel.AutoString(), nullable=False),
        sa.Column("p1_es", sqlmodel.AutoString(), nullable=False),
        sa.Column("p1_fr", sqlmodel.AutoString(), nullable=False),
        sa.Column("p2_en", sqlmodel.AutoString(), nullable=False),
        sa.Column("p2_es", sqlmodel.AutoString(), nullable=False),
        sa.Column("p2_fr", sqlmodel.AutoString(), nullable=False),
        sa.Column("skills", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "blogpost",
        sa.Column("slug", sqlmodel.AutoString(), nullable=False),
        sa.Column("date", sqlmodel.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.AutoString(), nullable=False),
        sa.Column("title_en", sqlmodel.AutoString(), nullable=False),
        sa.Column("title_es", sqlmodel.AutoString(), nullable=False),
        sa.Column("title_fr", sqlmodel.AutoString(), nullable=False),
        sa.Column("excerpt_en", sqlmodel.AutoString(), nullable=False),
        sa.Column("excerpt_es", sqlmodel.AutoString(), nullable=False),
        sa.Column("excerpt_fr", sqlmodel.AutoString(), nullable=False),
        sa.Column("content_en", sqlmodel.AutoString(), nullable=False),
        sa.Column("content_es", sqlmodel.AutoString(), nullable=False),
        sa.Column("content_fr", sqlmodel.AutoString(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("blogpost", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_blogpost_slug"), ["slug"], unique=True)

    op.create_table(
        "chatfeedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_message", sqlmodel.AutoString(), nullable=False),
        sa.Column("assistant_reply", sqlmodel.AutoString(), nullable=False),
        sa.Column("is_helpful", sa.Boolean(), nullable=False),
        sa.Column("module", sqlmodel.AutoString(), nullable=True),
        sa.Column("category", sqlmodel.AutoString(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chatmessage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.AutoString(), nullable=False),
        sa.Column("content", sqlmodel.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chatmessage", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chatmessage_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "chattriggerresponse",
        sa.Column("module", sqlmodel.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.AutoString(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("triggers", sa.JSON(), nullable=True),
        sa.Column("answers_en", sa.JSON(), nullable=True),
        sa.Column("answers_es", sa.JSON(), nullable=True),
        sa.Column("answers_fr", sa.JSON(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chattriggerresponse", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_chattriggerresponse_module"), ["module"], unique=False
        )

    op.create_table(
        "experience",
        sa.Column("company", sqlmodel.AutoString(), nullable=False),
        sa.Column("role", sqlmodel.AutoString(), nullable=False),
        sa.Column("period", sqlmodel.AutoString(), nullable=False),
        sa.Column("description_en", sa.JSON(), nullable=True),
        sa.Column("description_es", sa.JSON(), nullable=True),
        sa.Column("description_fr", sa.JSON(), nullable=True),
        sa.Column("tech", sa.JSON(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "livechatsession",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sqlmodel.AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("session_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("livechatsession", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_livechatsession_session_id"), ["session_id"], unique=True
        )

    op.create_table(
        "project",
        sa.Column("title", sqlmodel.AutoString(), nullable=False),
        sa.Column("description_en", sqlmodel.AutoString(), nullable=False),
        sa.Column("description_es", sqlmodel.AutoString(), nullable=False),
        sa.Column("description_fr", sqlmodel.AutoString(), nullable=False),
        sa.Column("tech", sa.JSON(), nullable=True),
        sa.Column("link", sqlmodel.AutoString(), nullable=True),
        sa.Column("github", sqlmodel.AutoString(), nullable=True),
        sa.Column("image", sqlmodel.AutoString(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "visitorlog",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("path", sqlmodel.AutoString(), nullable=False),
        sa.Column("method", sqlmodel.AutoString(), nullable=False),
        sa.Column("locale", sqlmodel.AutoString(), nullable=False),
        sa.Column("user_agent", sqlmodel.AutoString(), nullable=True),
        sa.Column("referrer", sqlmodel.AutoString(), nullable=True),
        sa.Column("ip_hash", sqlmodel.AutoString(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("visitorlog", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_visitorlog_ip_hash"), ["ip_hash"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_visitorlog_path"), ["path"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("visitorlog", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_visitorlog_path"))
        batch_op.drop_index(batch_op.f("ix_visitorlog_ip_hash"))

    op.drop_table("visitorlog")
    op.drop_table("project")
    with op.batch_alter_table("livechatsession", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_livechatsession_session_id"))

    op.drop_table("livechatsession")
    op.drop_table("experience")
    with op.batch_alter_table("chattriggerresponse", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chattriggerresponse_module"))

    op.drop_table("chattriggerresponse")
    with op.batch_alter_table("chatmessage", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_chatmessage_session_id"))

    op.drop_table("chatmessage")
    op.drop_table("chatfeedback")
    with op.batch_alter_table("blogpost", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_blogpost_slug"))

    op.drop_table("blogpost")
    op.drop_table("about")
    # ### end Alembic commands ###
