"""Add TelegramMessageMap table

Revision ID: 7465209f01ef
Revises: 3a40d1099870
Create Date: 2026-05-19 20:22:34.319078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7465209f01ef'
down_revision: Union[str, Sequence[str], None] = '3a40d1099870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegrammessagemap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegrammessagemap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegrammessagemap_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telegrammessagemap_telegram_message_id'), ['telegram_message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegrammessagemap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegrammessagemap_telegram_message_id'))
        batch_op.drop_index(batch_op.f('ix_telegrammessagemap_session_id'))

    op.drop_table('telegrammessagemap')
    # ### end Alembic commands ###
